---
- name: "Manage disk partitions"
  tags:
    - disk
    - disk.partition
  ansible.builtin.import_tasks: "partition/{{ ansible_system }}.yaml"
  when: disk_partitions | length > 0

- name: "Manage logical volume groups"
  tags:
    - disk
    - disk.mdraid
  ansible.builtin.import_tasks: mdraid.yaml
  when: disk_mdraids | length > 0

- name: "Manage logical volume groups"
  tags:
    - disk
    - disk.vg
  ansible.builtin.import_tasks: vg.yaml
  when: disk_vgs | length > 0

- name: "Manage logical volumes"
  tags:
    - disk
    - disk.lvol
  ansible.builtin.import_tasks: lvol.yaml
  when: disk_lvols | length > 0

- name: "Manage filesystems"
  tags:
    - disk
    - disk.filesystem
  ansible.builtin.import_tasks: "filesystem/{{ ansible_system }}.yaml"
  when: disk_filesystems | length > 0

- name: "Manage filesystem mounts"
  tags:
    - disk
    - disk.mount
  ansible.builtin.import_tasks: mount.yaml
  when: |-
    ansible_os_family == 'RedHat' or
    ansible_os_family == 'Debian'

- name: "Manage drive mounts"
  tags:
    - disk
    - disk.credential
    - disk.drive
    - disk.image
  ansible.builtin.import_tasks: drive.yaml
  when:
    - ansible_os_family == 'Windows'
    - (disk_drives | length + disk_images | length) > 0
