- name: "Manage filesystem mount"
  ansible.posix.mount:
    src: "{{ item['dev'] | default(omit) }}"
    path: "{{ item['path'] | mandatory }}"
    fstype: "{{ item['fstype'] | mandatory }}"
    opts: "{{ item['opts'] | default([]) | join(' ') | default('defatults',true) }}"
    passno: "{{ item['passno'] | default(omit) }}"
    dump: "{{ item['dump'] | default(omit) }}"
    state: "{{ item['state'] | mandatory }}"
  loop: "{{ disk_mounts }}"
  loop_control:
    label: "{{ item['dev'] }} {{ item['path'] | default('') }} {{ item['state'] }}"
