---
- name: "Manage Windows filesystem"
  community.windows.win_format:
    allocation_unit_size: "{{ item['allocation_unit_size'] | default(omit) }}"
    compress: "{{ item['compress'] | default(omit) }}"
    drive_letter: "{{ item['drive_letter'] | mandatory }}"
    file_system: "{{ item['file_system'] | default(omit) }}"
    force: "{{ item['force'] | default(omit) }}"
    full: "{{ item['full'] | default(omit) }}"
    integrity_streams: "{{ item['integrity_streams'] | default(omit) }}"
    label: "{{ item['label'] | default(omit) }}"
    large_frs: "{{ item['large_frs'] | default(omit) }}"
    new_label: "{{ item['new_label'] | default(omit) }}"
    path: "{{ item['path'] | default(omit) }}"
  loop: "{{ disk_filesystems }}"
  loop_control:
    label: >-
      {{ item['drive_letter'] | default('') }}
      {{ item['label'] | default('') }}
  become: true
